Write a NumPy program to multiply the values of two given vectors.

In [2]:
import numpy as np

In [3]:
a = np.random.randint(0,10,8)
print(a)
b = np.random.randint(10,20,8)
print(b)
print(a*b)

[7 1 5 1 4 1 5 7]
[15 11 11 15 17 19 10 19]
[105  11  55  15  68  19  50 133]
